env:
  browser: true
  es2021: true
  node: true
  jest: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-unused-vars: warn
  simple-import-sort/sort: warn
parser: '@babel/eslint-parser'
plugins:
  - '@babel'
  - simple-import-sort
